"@context":
  "@base": http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  owl: http://www.w3.org/2002/07/owl#
  xsd: http://www.w3.org/2001/XMLSchema#
  dc: http://purl.org/dc/terms/
  dce: http://purl.org/dc/elements/1.1/
  dcterms: http://purl.org/dc/terms/1.1/
  faldo: http://biohackathon.org/resource/faldo#
  foaf: http://xmlns.com/foaf/0.1/
  oa: http://www.w3.org/ns/oa#
  idot: http://identifiers.org/
  void: http://rdfs.org/ns/void#
  doap: http://usefulinc.com/ns/doap#
  pav: http://purl.org/pav/

  id: "@id"
  label: rdfs:label
  comment: rdfs:comment
  description: dce:description
  source: dce:source
  publisher: dce:publisher
  mailing_list: doap:mailing-list
  createdWith: pav:createdWith
  wasDerivedFrom: pav:wasDerivedFrom
  preferredPrefix: idot:preferredPrefix
  alternatePrefix: idot:alternatePrefix
  identifierPattern: idot:identifierPattern
  exampleIdentifier: idot:exampleIdentifier

  Class: owl:Class

  products: void:subset

  type:
    "@id": rdf:type
    "@type": "@id"
  created:
    "@id": dcterms:created
    "@type": xsd:dateTime
  creator:
    "@id": dcterms:creator
    "@type": "@id"
  depiction:
    "@id": foaf:depiction
    "@type": "@id"
  publications: dcterms:publication
  source: dce:source
  subClassOf: owl:subClassOf
  title: dce:title
  homepage:
    "@id": foaf:homepage
    "@type": "@id"
  page:
    "@id": foaf:page
    "@type": "@id"
  ontologies: dcterms:hasPart


## ----------------------------------------
## BUSINESS STARTS HERE
## ----------------------------------------

id: http://obolibrary.org
title: OBO Library VERY EXPERIMENTAL BROWSER
description: "A set of ontology libraries for doing useful stuff. This is a demo, DO NOT TRUST ANY INFO YOU SEE HERE"

ontologies:

## UBERON

  - id: uberon
    type: owl:Ontology
    label: Uberon
    title: Uberon multi-species anatomy ontology
    description: Uberon is an integrated cross-species anatomy ontology representing a variety of entities classified according to traditional anatomical criteria such as structure, function and developmental lineage. The ontology includes comprehensive relationships to taxon-specific anatomical ontologies, allowing integration of functional, phenotype and expression data
    homepage: http://uberon.org
    page: http://en.wikipedia.org/wiki/Uberon
    twitter: uberanat
    google_plus: "+UberonOrg"
    mailing_list: https://lists.sourceforge.net/lists/listinfo/obo-anatomy
    canonical: uberon.owl
    taxon:
      id: NCBITaxon:33208
      label: Metazoa
    domain: anatomy
    repository: https://github.com/obophenotype/uberon
    tracker: https://github.com/obophenotype/uberon/issues
    releases: http://purl.obolibrary.org/obo/uberon/releases/
    contact:
      email: cjmungall@lbl.gov
      label: Chris Mungall
    publications:
      - id: http://www.ncbi.nlm.nih.gov/pubmed/22293552
    depicted_by: http://uberon.github.io/images/u-logo.jpg
    redirects:
      - match: "releases/"
        url: "http://svn.code.sf.net/p/obo/svn/uberon/releases/"
      - match: ""
        url: "http://berkeleybop.org/ontologies/uberon/"
    dependencies:
     - id: go
       subset: uberon/go_import.owl
     - id: cl
       subset: uberon/cl_import.owl
     - id: chebi
       subset: uberon/chebi_import.owl
     - id: pr
       subset: uberon/pr_import.owl
    products:
     - id: uberon.owl
       type: owl:Ontology
       title: Uberon
       is_canonical: true
     - id: uberon/ext.owl
       type: owl:Ontology
       description: Uberon extended
       title: Uberon edition that includes subsets of other ontologies
       mireots_from: cl
       mireots_from: pr
       mireots_from: envo
       mireots_from: go
       mireots_from: pato
       mireots_from: ncbitaxon
     - id: uberon/basic.obo
       title: Uberon basic
       description: Uberon edition that excludes external ontologies and most relations
       format: obo
       type: obo-basic-ontology
     - id: uberon/bridge/uberon-bridge-to-zfa.owl
       type: BridgeOntology
       page: https://github.com/obophenotype/uberon/wiki/inter-anatomy-ontology-bridge-ontologies
       title: Uberon bridge to ZFA
       description: Taxonomic equivalence axioms connecting zebrafish-specific classes to generic uberon counterparts
       connects:
         - id: uberon
         - id: zfa
     - id: uberon/bridge/uberon-bridge-to-ma.owl
       type: BridgeOntology
       page: https://github.com/obophenotype/uberon/wiki/inter-anatomy-ontology-bridge-ontologies
       title: Uberon bridge to MA
       description: Taxonomic equivalence axioms connecting adult mouse specific classes to generic uberon counterparts
       connects:
         - id: uberon
         - id: ma
     - id: uberon/composite-metazoan.owl
       type: MergedOntology
       title: Uberon composite metazoan ontology
       page: https://github.com/obophenotype/uberon/wiki/Multi-species-composite-ontologies
       taxon: Metazoa
       mireots_from: zfa
       mireots_from: xao
       mireots_from: fbbt
       mireots_from: wbbt
       mireots_from: ma
       mireots_from: fma
       mireots_from: emapa
       mireots_from: ehdaa2
     - id: uberon/composite-vertebrate.owl
       type: MergedOntology
       title: Uberon composite vertebrate ontology
       page: https://github.com/obophenotype/uberon/wiki/Multi-species-composite-ontologies
       taxon: Metazoa
       mireots_from: zfa
       mireots_from: xao
       mireots_from: fbbt
       mireots_from: wbbt
       mireots_from: ma
       mireots_from: fma
       mireots_from: emapa
       mireots_from: ehdaa2

## GO

  - id: go
    label: GO
    title: Gene Ontology
    twitter: news4go
    tracker: http://sourceforge.net/p/geneontology/ontology-requests/
    termgenie: http://go.termgenie.org
    taxon:
      id: NCBITaxon:1
      label: All life
    domain: biology
    dependencies:
     - id: uberon
       subset: go/extensions/uberon_import.owl
     - id: cl
       subset: go/extensions/cl_import.owl
     - id: ncbitaxon
       subset: go/extensions/ncbitaxon_import.owl
     - id: ro
       subset: go/extensions/ro_import.owl
     - id: go/extensions/go-bridge-to-nifstd.owl
       type: BridgeOntology
       title: GO bridge to NIFSTD
       description: Bridging axioms between nifstd and go
       connects:
         - id: nifstd
         - id: go
    products:
     - id: go.owl
    depicted_by: http://geneontology.org/sites/default/files/go-logo-icon.mini__0.png

## CL

  - id: cl
    label: Cell Ontology
    title: Cell Ontology
    description: The Cell Ontology is designed as a structured controlled vocabulary for cell types. This ontology was constructed for use by the model organism and other bioinformatics databases, where there is a need for a controlled vocabulary of cell types. This ontology is not organism specific it covers cell types from prokaryotes to mammals. However, it excludes plant cell types, which are covered by PO.
    taxon:
      id: NCBITaxon:33208
      label: Metazoa
    domain: cells
    tracker: https://code.google.com/p/cell-ontology/issues/list
    termgenie: http://cl.termgenie.org
    mailing_list: https://lists.sourceforge.net/lists/listinfo/obo-cell-type
    dependencies:
     - id: uberon
     - id: go
    canonical: cl.owl
    products:
     - id: cl.owl
     - id: cl.obo
     - id: cl/cl-basic.obo

## RO

  - id: ro
    title: Relations Ontology
    canonical: ro.owl
    tracker: https://code.google.com/p/obo-relations/issues/list
    mailing_list: https://lists.sourceforge.net/lists/listinfo/obo-relations
    domain: relations
    jobs:
      - id: http://build.berkeleybop.org/job/build-ro
        type: DryRunBuild
    products:
     - id: ro.owl
     - id: ro.obo
     - id: ro/ro-interaction.owl

## CHEBI

  - id: chebi
    alternatePrefix: ChEBI
    title: Chemical entities of biological interest
    description: A structured classification of chemical compounds of biological relevance.
    contact:
      email: hastings@ebi.ac.uk
      label: Janna Hastings
    domain: biochemistry
    homepage: http://www.ebi.ac.uk/chebi
    page: http://www.ebi.ac.uk/chebi/init.do?toolBarForward=userManual
    products:
      - id: chebi.owl
      - id: chebi.obo
    tracker: https://sourceforge.net/p/chebi/curator-requests/

## OBA

  - id: oba
    title: Ontology of Biological Attributes
    description: A collection of biological attributes (traits) covering all kingdoms of life. Incorporates VT (vertebrate trait ontology) and TO (plant trait ontology). Extends PATO.
    contact:
      email: cjmungall@lbl.gov
      label: Chris Mungall
    jobs:
      - id: http://build.berkeleybop.org/job/build-bio-attributes
        type: DryRunBuild
    termgenie: http://oba.termgenie.org
    domain: phenotype
    homepage: http://wiki.geneontology.org/index.php/Extensions/x-attribute
    page: http://wiki.geneontology.org/index.php/Extensions/x-attribute
    products:
      -
        id: oba.owl
        id: oba.obo

## HP

  - id: hp
    alternativePrefix: HPO
    description: The Human Phenotype Ontology is being developed to provide a structured and controlled vocabulary for the phenotypic features encountered in human hereditary and other disease. Our goal is to provide resource for the computational analysis of the human phenome, with a current focus on monogenic diseases listed in the Online Mendelian Inheritance in Man (OMIM) database, for which annotations are also provided.
    domain: phenotype
    homepage: http://www.human-phenotype-ontology.org/
    contact:
      email: peter.robinson@charite.de
      label: Peter Robinson
    products:
      - id: hp.owl
      - id: hp.obo
    taxon:
      id: NCBITaxon:9606
      label: Homo sapiens
    title: human phenotype ontology
    tracker: https://sourceforge.net/p/obo/human-phenotype-requests/
    termgenie: http://hp.termgenie,org

## MP

  - id: mp
    title: Mammalian phenotype
    description: The Mammalian Phenotype Ontology is under development as a community effort to provide standard terms for annotating mammalian phenotypic data.
    homepage: http://www.informatics.jax.org/searches/MP_form.shtml
    contact:
      email: pheno@jax.org
      label: JAX phenotype list
    domain: phenotype
    products:
      - id: mp.owl
      - id: mp.obo
    taxon:
      id: NCBITaxon:10088
      label: Mus
    tracker: https://sourceforge.net/p/obo/mammalian-phenotype-requests/
    termgenie: http://mp.termgenie.org

## FBbt

  - id: fbbt
    preferredPrefix: FBbt
    contact:
      email: djs93@gen.cam.ac.uk
      label: David Osumi-Sutherland
    description: A structured controlled vocabulary of the anatomy of Drosophila melanogaster
    domain: anatomy
    homepage: " http://purl.obolibrary.org/obo/fbbt"
    products:
      - id: fbbt.owl
    taxon:
      id: NCBITaxon:7227
      label: Drosophila
    title: Drosophila gross anatomy
    tracker: http://purl.obolibrary.org/obo/fbbt/tracker

## NCBITaxon
#
#  - id: ncbitaxon
#    preferredPrefix: NCBITaxon
#    title: NCBI organismal classification
#    contact:
#      email: obo-taxonomy@lists.sourceforge.net
#      label: obo-taxonomy-list
#    description: The NCBITaxon ontology is an automatic translation of the NCBI taxonomy (a taxonomic classification of living organisms and associated artifacts) database into obo/owl.
#    source: http://www.ncbi.nlm.nih.gov/taxonomy
#    wasDerivedFrom: ftp://ftp.ebi.ac.uk/pub/databases/taxonomy/taxonomy.dat
#    createdWith: http://owltools.googlecode.com/
#    domain: taxonomy
#    homepage: http://www.obofoundry.org/wiki/index.php/NCBITaxon:Main_Page
#    page: http://www.ncbi.nlm.nih.gov/taxonomy
#    isInferred: true
#    jobs:
#      - id: http://build.berkeleybop.org/job/build-ncbitaxon/
#        type: ReleaseBuild
#    products:
#      - id: ncbitaxon.owl
#      - id: ncbitaxon/subsets/taxslim.owl


## FMA

  - id: fma
    contact:
      email: mejino@comcast.net
      label: Onard Mejino
    description: Obo format translation of the FMA, omitting all relationships other than is_a, part_of and has_part. Future versions of fma_obo will include more relationships
    domain: anatomy
    homepage: http://sig.biostr.washington.edu/projects/fm/index.html
    page: http://en.wikipedia.org/wiki/Foundational_Model_of_Anatomy
    publications:
      - id: http://www.ncbi.nlm.nih.gov/pubmed/18688289
      - id: http://www.ncbi.nlm.nih.gov/pubmed/18360535
      - id: http://www.ncbi.nlm.nih.gov/pubmed/16779026
    products:
     - id: fma.owl
    taxon:
      id: NCBITaxon:9606
      label: Homo sapiens
    title: Foundational Model of Anatomy (subset)
    tracker: https://sourceforge.net/p/obo/foundational-model-of-anatomy-fma-requests/

## IAO

  - id: iao
    contact:
      email: alanruttenberg@gmail.com
      label: Alan Ruttenberg
    description: "The Information Artifact Ontology (IAO) is a new ontology of information entities, originally driven by work by the OBI digital entity and realizable information entity branch. "
    domain: information
    homepage: http://purl.obolibrary.org/obo/iao
    page: http://code.google.com/p/information-artifact-ontology/
    products:
      - id: iao.owl

      - id: iao/d-acts.owl
        title: ontology of document acts
        description: "An ontology based on a theory of document acts describing what people can do with documents"
        contact:
          email: mbrochhausen@gmail.com
          label: Mathias Brochhausen

    title: Information Artifact Ontology
    tracker: http://code.google.com/p/information-artifact-ontology/issues/list

## RS

  - id: rs
    contact:
      email: rnigam@mcw.edu
      label: Rajni Nigam
    description: Ontology of rat strains
    homepage: http://rgd.mcw.edu/
    publications:
      - id: http://www.ncbi.nlm.nih.gov/pubmed/24267899
    products:
      - id: rs.owl
    title: Rat Strain Ontology

## DPO

  - id: fbcv
    title: Drosophila Phenotype Ontology
    preferredPrefix: FBcv
    products:
      - id: fbcv.owl
    contact:
      email: djs93@gen.cam.ac.uk
      label: David Osumi-Sutherland
    description: "An ontology of commonly encountered and/or high level Drosophila phenotypes.  It has significant formalisation - utilising terms from GO, CL, PATO and the Drosophila anatomy ontology.  It has been used by FlyBase for > 159000 annotations of phenotype"
    homepage: http://www.flybase.org/

## PATO

  - id: pato
    title: Phenotypic quality
    description: Phenotypic qualities (properties). This ontology can be used in conjunction with other ontologies such as GO or anatomical ontologies to refer to phenotypes. Examples of qualities are red, ectopic, high temperature, fused, small, edematous and arrested.
    contact:
      email: geg18@aber.ac.uk
      label: George Gkoutos
    domain: phenotype
    homepage: http://obofoundry.org/wiki/index.php/PATO:Main_Page
    repository: https://github.com/gkoutos/pato
    tracker: https://github.com/gkoutos/pato/issues
    jobs:
      - id: http://build.berkeleybop.org/job/build-pato
        type: DryRunBuild
    products:
      - id: pato.owl
      - id: pato.obo

  - build: {checkout: 'git clone  https://github.com/AgriculturalSemantics/agro.git',
      infallible: 1, method: vcs, path: ., system: git}
    contact: {email: c.aubert@cgiar.org, github: celineaubert, label: Celine Aubert}
    dependencies:
    - {id: envo}
    - {id: uo}
    - {id: ro}
    - {id: pato}
    - {id: chebi}
    - {id: iao}
    description: Ontology of agronomic practices, agronomic techniques, and agronomic
      variables used in agronomic experiments
    domain: agronomy
    homepage: https://github.com/AgriculturalSemantics/agro
    id: agro
    jobs:
    - {id: 'https://travis-ci.org/AgriculturalSemantics/agro', type: travis-ci}
    layout: ontology_detail
    license: {label: CC-BY, logo: 'http://mirrors.creativecommons.org/presskit/buttons/80x15/png/by.png',
      url: 'http://creativecommons.org/licenses/by/3.0/'}
    mailing_list: https://groups.google.com/group/agronomyOntology
    ontology_purl: http://purl.obolibrary.org/obo/agro.owl
    products:
    - {id: agro.owl, ontology_purl: 'http://purl.obolibrary.org/obo/agro.owl'}
    title: Agronomy Ontology
    tracker: https://github.com/AgriculturalSemantics/agro/issues/