"@context":


ontologies:

## RETOMUSIC
  - id: retomusic
    preferredPrefix: RETOMUSIC
    title: RetoMusic
    uri: http://www.contactomovil.com.co/ontologias/musica_zonadetrabajo
    description: "Reto Music"
    reasoner: OWL2
    oboSlims: false
    hierarchical_property:
      - http://www.contactomovil.com.co/ontologias/musica_contenidosyrelaciones#essobre
      - http://www.contactomovil.com.co/ontologias/musica_contenidosyrelaciones#tienerelacion
    ontology_purl: http://www.contactomovil.com.co/ontologias/musica_zonadetrabajo.owl
