"@context":



ontologies:
## EDAM
  - id: edam
    preferredPrefix: EDAM
    title: EDAM bioinformatics ontology
    uri: http://edamontology.org
    description: EDAM is a simple ontology of well established, familiar concepts that are prevalent within bioinformatics, including types of data and data identifiers, data formats, operations and topics. EDAM provides a set of terms with synonyms and definitions - organised into an intuitive hierarchy for convenient use.
    homepage: http://edamontology.org
    mailing_list: edam@elixir-dk.org
    definition_property:
      - http://www.geneontology.org/formats/oboInOwl#hasDefinition
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    base_uri:
      - http://edamontology.org/data_
      - http://edamontology.org/identifier_
      - http://edamontology.org/topic_
      - http://edamontology.org/format_
    oboSlims: false
    ontology_purl: http://edamontology.org/EDAM.owl


## EDAM7
  - id: edam7
    preferredPrefix: EDAM7
    title: EDAM bioinformatics ontology
    uri: http://edamontology.org
    description: EDAM is a simple ontology of well established, familiar concepts that are prevalent within bioinformatics, including types of data and data identifiers, data formats, operations and topics. EDAM provides a set of terms with synonyms and definitions - organised into an intuitive hierarchy for convenient use.
    homepage: http://edamontology.org
    mailing_list: edam@elixir-dk.org
    definition_property:
      - http://www.geneontology.org/formats/oboInOwl#hasDefinition
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    base_uri:
      - http://edamontology.org/data_
      - http://edamontology.org/identifier_
      - http://edamontology.org/topic_
      - http://edamontology.org/format_
    oboSlims: false
    ontology_purl: http://edamontology.org/EDAM.owl


